### ISSUE TITLE
Fail to create AS group using module huaweicloudstack_as_group_v1

### ISSUE THREAD

**Issue by polidori7** [huaweicloud/terraform-provider-huaweicloudstack#15]
I'm trying to create AS group using HuaweiCloudStack provider lasted version (unversioned) and terraform 0.12.13.
I followed the documentation https://github.com/huaweicloud/terraform-provider-huaweicloudstack to install.

![image](https://user-images.githubusercontent.com/59088660/72347031-f5db6c80-36b5-11ea-8ab1-1331ae5a4449.png)

My .tf file was like this:

![image](https://user-images.githubusercontent.com/59088660/72346772-5cac5600-36b5-11ea-8da4-74c1aa39d464.png)

But I received this error message:

![image](https://user-images.githubusercontent.com/59088660/72346277-66818980-36b4-11ea-895d-3e43e2b81944.png)

I double check if subnet was created correctly and was Ok:

![image](https://user-images.githubusercontent.com/59088660/72346714-430b0e80-36b5-11ea-8b46-80bc4a8c3e2a.png)

![image](https://user-images.githubusercontent.com/59088660/72346836-7a79bb00-36b5-11ea-8295-50c396018f70.png)

**Comment by ShiChangkuo** [comment]
@polidori7 Maybe you can use the id of network, the format likes huaweicloudstack_networking_network_v2.xxx.id

**Comment by ShiChangkuo** [comment]
@polidori7 Since we have pushed the repository to terraform-providers, it is never used again. Please go to https://github.com/terraform-providers/terraform-provider-huaweicloudstack.
