### ISSUE TITLE
Fail to use Elastic Load Balancer Resources with HCS 6.5.1

### ISSUE THREAD

**Issue by polidori7** [huaweicloud/terraform-provider-huaweicloudstack#16]
I followed the guide on https://github.com/huaweicloud/terraform-provider-huaweicloudstack to prepare the environment to use Huaweicloudstack provider

![image](https://user-images.githubusercontent.com/59088660/72347848-d0e7f900-36b7-11ea-93ae-459780c055ad.png)

When I try to use whatever ELB resource show error message that ELB modules aren't supported

![image](https://user-images.githubusercontent.com/59088660/72348264-cda13d00-36b8-11ea-94b6-5839971936d5.png)

**Comment by ShiChangkuo** [comment]
@polidori7 It looks like the provider doesn't support ELB. We have added ELB resources since v1.1.0, and you can upgrade to the latest version then have a try. Good luck!

**Comment by ShiChangkuo** [comment]
@polidori7 Since we have pushed the repository to terraform-providers, it is never used again. Please go to https://github.com/terraform-providers/terraform-provider-huaweicloudstack.
