### ISSUE TITLE
How to install a license for a stack system of HUAWEI switch-S

### ISSUE THREAD

**Issue by dcmaker-123** [huaweicloud/terraform-provider-huaweicloudstack#33]
I want to know how to install a license for the switch after stacking and merge, is there any help from a god?

**Comment by Angelle-gao** [comment]
Different from the license for a standalone switch, a stack license must contain license control items for all stack members.
For more information, you can refer to the guideline [here](https://support.huawei.com/enterprise/en/doc/EDOC1100195305).
