### ISSUE TITLE
No provider documentation(or broken docu links)

### ISSUE THREAD

**Issue by lipingtababa** [huaweicloud/terraform-provider-huaweicloudstack#4]
Please kindly provide documentation for all the resources and data.

The HuaweiCloud Provider detailed pages on terraform.io always return 404 error while the index page works fine.

For Example 
https://www.terraform.io/docs/providers/huaweicloud/r/compute_instance_v2.html

![404](https://user-images.githubusercontent.com/1465219/67126517-8a3d4c80-f1f7-11e9-8dbc-7a1d4ee2d7f9.PNG)

https://www.terraform.io/docs/providers/huaweicloud/d/antiddos_v1.html
https://www.terraform.io/docs/providers/huaweicloud/r/compute_keypair_v2.html

**Comment by ShiChangkuo** [comment]
@lipingtababa the docs were maintained by terraform website, checking the network quality would fix the issue.

**Comment by lipingtababa** [comment]
The links work now. 
One quesiton: Does HuaweiCloudStack provider share the exact same documentation with HuaweiCloud provider? If so, can I use [HuaweiCloud Provider ](https://github.com/terraform-providers/terraform-provider-huaweicloud) to provision the private cloud with a small modification of endpoint?

**Comment by ShiChangkuo** [comment]
For now we can get the documentation in ./website/docs which is different with HuaweiCloud provider.
and the endpoints should be obtained in LLD of HCS.
