### ISSUE TITLE
Terraform Provider Development Program - Review

### ISSUE THREAD

**Issue by cgriggs01** [huaweicloud/terraform-provider-huaweicloudstack#8]
Hey Team, 

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. The review was done on the develop branch at git commit `0ac93c6`

- [x] One of our Terraform Ecosystem engineers built a linter to help align coding best practices for providers. You should use it along with your development. https://github.com/bflad/tfproviderlint

- [x] The changelog need its first entry, we use a specific (Unreleased) tag that is updated by a bot during a versioned release. Something like `## 1.0.0 (Unreleased)` would work .  

- [x] All providers in the terraform-providers/ GitHub org have a TravisCI check run on each PR that is opened. Can you please add a .travis.yaml file to make the [standard configuration](https://github.com/terraform-providers/terraform-provider-null/blob/master/.travis.yml)

- [x] If an object doesn’t require a function like update in the [AS_Configuration](https://github.com/huaweicloud/terraform-provider-huaweicloudstack/blob/master/huaweicloudstack/resource_huaweicloudstack_as_configuration_v1.go#L21) can be removed if not used. 

- [x] If a resource cannot be found(404) in the READ function, we should do a d.SetId("") to remove it from the statefile. You also wouldn't need to return an error then. Terraform will just treat it as a resource that never existed and try and create it.

- [x] I was able to run the acceptance tests, many passed but a few have failed. I’ve attached the testing output, could you help to get this tests all passing?
[test.txt](https://github.com/huaweicloud/terraform-provider-huaweicloudstack/files/3817402/test.txt)

Thanks, Im looking forward to finalizing this provider with you'll!

**Comment by niuzhenguo** [comment]
@cgriggs01 Thanks, will address that soon!

**Comment by niuzhenguo** [comment]
- If a resource cannot be found(404) in the READ function, we should do a d.SetId("") to remove it from the statefile. You also wouldn't need to return an error then. Terraform will just treat it as a resource that never existed and try and create it.

@cgriggs01 Regarding this, we have a CheckDeleted function to handle it. https://github.com/huaweicloud/terraform-provider-huaweicloudstack/blob/master/huaweicloudstack/util.go#L32-L41

**Comment by cgriggs01** [comment]
Oh I see now, thanks for the clarification, you can disregard that item.

**Comment by niuzhenguo** [comment]
@cgriggs01 All issues have been addressed, and please try the tests again, thanks!

**Comment by cgriggs01** [comment]
Hey @niuzhenguo,

Yes, the tests are passing. Everything looks to be address now. I am ready to move forward with the migration and release fo the provider. 

I'll be closing this issue now.
