### ISSUE TITLE
Fail to create Autoscaling Group resource

### ISSUE THREAD

**Issue by polidori7** [huaweicloud/terraform-provider-huaweicloudstack#9]
Using  huaweicloudstack_as_group_v1 module show an error message describing that arguments "networks" and "security_groups" are not expected to happen inside the block but on documentation says: "networks" and "security_groups" are required information.

**Comment by ShiChangkuo** [comment]
@polidori7 Thanks for raising, it looks like a syntax error. Lists of objects can be created with repeated blocks, using this structure:
```hcl
service {
    key = "value"
}

service {
    key = "value"
}
```
Obviously, the documentation gives an outdated usage , and we will correct these mistakes.

**Comment by henriquepolidori** [comment]
I followed this guide https://github.com/terraform-providers/terraform-provider-huaweicloudstack and test again create an AS group module using the latest huaweicloudstack provider version with Huawei Cloud Stack 6.5.1 but failed again:

As you can see, I received a message AS.2013 (invalid subnet, but before to input the value, I double checked the subnet information through huawei cloudstack networking subnet_v2 module. I tried huawei cloudstack networking subnet_v2.xxxx.id, ID directly. 

![image](https://user-images.githubusercontent.com/29752846/73172545-06daa380-40e2-11ea-8b78-3d35c92c0278.png)


![image](https://user-images.githubusercontent.com/29752846/73172552-09d59400-40e2-11ea-9c83-83b08d39eb11.png)

version 
![image](https://user-images.githubusercontent.com/29752846/73173024-26260080-40e3-11ea-8de3-cd732de0ab59.png)

**Comment by ShiChangkuo** [comment]
@polidori7 Maybe you can use the id of network, the format likes **huaweicloudstack_networking_network_v2.xxx.id**

and the version of huaweicloudstack provider maybe not the latest, it should be:
**+ provider.huaweicloudstack v1.1.0**
Please have a check, thanks.

**Comment by henriquepolidori** [comment]
Friend,

As you can see, now I'm using this version + provider.huaweicloudstack v1.1.0 but the same issue is happening to create AS group.

![image](https://user-images.githubusercontent.com/29752846/73841054-7a726400-47f8-11ea-86b2-67e6061aee26.png)


![image](https://user-images.githubusercontent.com/29752846/73841234-ec4aad80-47f8-11ea-83c3-d3d0c4d3b836.png)

I already tested using new terraform verison 0.12.20 and the same issue happen.

Best Regards

**Comment by ShiChangkuo** [comment]
@henriquepolidori please try to use huaweicloudstack_networking_network_v2.xxx.id instead.

**Comment by henriquepolidori** [comment]
Friend,

Now I was able to create AS group. Very Good, but when I tried to destroy the environment I receive this message below:

![image](https://user-images.githubusercontent.com/29752846/74035652-69ad2400-4999-11ea-9961-6e40ec0b069b.png)

Should I close this ticket and open new one or Is there a relationship in use AS group using huaweicloudstack_networking_network_v2.xxx.id with this error ?

**Comment by ShiChangkuo** [comment]
Opening a new issue will be better.

BTW, you can also give the error message in text format, thanks.

**Comment by henriquepolidori** [comment]
thanks
